const config = {
  daysOfWeek: ["Hétfő", "Kedd", "Szerda", "Csütörtök", "Péntek"],

  timeSlots: [
    "7:50-8:35",
    "8:45-9:30",
    "9:40-10:25",
    "10:45-11:30",
    "11:40-12:25",
    "12:35-13:20",
    "13:30-14:15",
    
  ],
  classes: ["1.A", "1.B", "2.A", "2.B", "3.A", "3.B", "4.A", "4.B"],
  subjects: [
    { name: "Matematika", teacher: "Tanár 1", quantity: 2 },
    { name: "Fizika", teacher: "Tanár 1", quantity: 1 },
    { name: "Fizika", teacher: "Tanár 1", quantity: 1 },
    { name: "Matematika2", teacher: "Tanár 2", quantity: 2 },
    { name: "Fizika2", teacher: "Tanár 2", quantity: 1 },
    { name: "Történelem", teacher: "Tanár 3", quantity: 2 },
    { name: "Történelem2", teacher: "Tanár 13", quantity: 2 },
    { name: "Polgari", teacher: "Tanár B", quantity: 1 },
    { name: "Foldrajz", teacher: "Tanár 4", quantity: 1 },
    { name: "Magyar", teacher: "Tanár 4", quantity: 2 },
    { name: "Szlovak", teacher: "Tanár 5", quantity: 2 },
    { name: "Magyar2", teacher: "Tanár 5", quantity: 2 },
    { name: "Szlovak2", teacher: "Tanár 6", quantity: 2 },
    { name: "Angol", teacher: "Tanár 6", quantity: 2 },
    { name: "Nemet", teacher: "Tanár 7", quantity: 2 },
    { name: "Angol2", teacher: "Tanár 7", quantity: 2 },
    { name: "Nemet2", teacher: "Tanár 8", quantity: 2 },
    { name: "Torna", teacher: "Tanár 8", quantity: 2 },
    { name: "Informatika", teacher: "Tanár 9", quantity: 2 },
    { name: "Kemia", teacher: "Tanár 9", quantity: 1 },
    { name: "Biologia", teacher: "Tanár 10", quantity: 1 },
    { name: "Kemia2", teacher: "Tanár 10", quantity: 1 },
    { name: "Biologia2", teacher: "Tanár 11", quantity: 1 },
    { name: "Spanyol", teacher: "Tanár 11", quantity: 1 },
    { name: "Francia", teacher: "Tanár 12", quantity: 1 },
    { name: "Francia2", teacher: "Tanár 12", quantity: 1 },
  ],
};

module.exports = config;
